### ISSUE TITLE
Bug: Crash After Clicking "基线编辑"

### ISSUE THREAD

**Issue by wensimehrp** [CDK6182CHR/qETRC#2]
![etrcBug](https://github.com/CDK6182CHR/qETRC/assets/145064583/fa54dc7b-6c7a-420b-8190-8afaf3755402)
~~*Wo Bu Li Jie*~~
### About The Bug

Everything is in the .gif pic.

**Comment by CDK6182CHR** [comment]
Thanks for your report. 
The "线路编辑" button is provided for editing a railway ("基线") that *already exists* in the diagram. However, when a new diagram is created (via "新建"), there is no railway in the diagram. 
I will fix this bug in next version.

**Comment by CDK6182CHR** [comment]
This problem is solved in the release of V1.5.3 (R46).
