### ISSUE TITLE
Bug(ish): Wrong Train Number 错误的车次

### ISSUE THREAD

**Issue by wensimehrp** [CDK6182CHR/qETRC#3]
### Description
我尝试这样做……
<img width="393" alt="image" src="https://github.com/CDK6182CHR/qETRC/assets/145064583/46d7b47d-2091-4bc2-8ff3-1d96587b849d">
<img width="398" alt="image" src="https://github.com/CDK6182CHR/qETRC/assets/145064583/feaebe7d-98ed-42a0-894d-b27dfc061f38">
我不确定这是不是一个bug，更像是一个逻辑错误。

简单来说，这三张分开的运行图所反映的真实情况是这样的：
<img width="376" alt="image" src="https://github.com/CDK6182CHR/qETRC/assets/145064583/569e4dc4-b466-405b-b7eb-2254cae84e3a">
在A-G Branch这张图上车次显示是正常的，但是在G Branch-F Branch这张图上显示是错误的。

上行/下行车次的显示没有考虑运行图中某一部分被扭转的情况。

**Comment by CDK6182CHR** [comment]
这不是一个bug。

本程序中，我们规定，线路里程表中里程递增方向为下行方向，程序内部一切与上下行有关的规定都严格遵从此定义。原则上程序内的上下行可以与实际线路的上下行没有关系。参见文档描述  https://qetrc.readthedocs.io/zh_CN/latest/data/rail.html#rail-concepts

实际操作中，如果你的F-G conj. 至GB方向为下行，那么线路可以按此方向组织。如果FB->F-G Conj.->GB方向行别改变，可以拆分成两条线路；F-G conj.至GB不必重复两遍。

或者也可以考虑启用显示完整车次的功能。

**Comment by wensimehrp** [comment]
谢谢
