### ISSUE TITLE
Bug: 任务栏置顶时的窗口位置无法调整的小问题

### ISSUE THREAD

**Issue by GitHubonline1396529** [CDK6182CHR/qETRC#4]
## 问题描述

**软件版本：qETRC-win64_V1.5.2_R45_20230930**

这个问题说起来有些可笑…… 但是是的，我的电脑 Windows 系统任务栏是置顶的，位于桌面最上方。

遇到了窗口位置无法调整的情况，因为窗口的标题栏位于桌面以外，被任务栏遮挡。

- 尝试使用快捷键 `Alt + <Space>` 打开窗口菜单，发现 `移动(M)` 选项是灰色的。
- 尝试使用快捷键 `<Win> + <Down>` 最小化窗口。再次点击全屏按钮发现标题栏再次飞出屏幕

如下图所示：

![遇到了窗口位置无法调整的情况](https://s2.loli.net/2023/11/13/WUzgqcFfGJmhAsD.png)

这不是一个严重的问题，因为我可以不使用最大化窗口。但是因为问题存在，所以在 issue 里面简单反馈一下。这算是一个 Bug 吗？

## 可能的复现方法

- Windows 版本：Windows 10 2H22 
- 将任务栏拖动到桌面最顶端

**Comment by GitHubonline1396529** [comment]
_**Here is an English translation of this Issue, for those people who are not native Chinese speakers ...**_

---

## Issue Description

**Software Version: qETRC-win64_V1.5.2_R45_20230930**

This might sound a bit silly... but yes, my Windows taskbar is set to be always on top, positioned at the top of the desktop.

I encountered a situation where I couldn't adjust the window position because the window's title bar was located outside of the desktop area and was obscured by the taskbar.

- Attempted to use the shortcut `Alt + <Space>` to open the window menu, but found that the `Move (M)` option was grayed out.
- Tried using the shortcut `<Win> + <Down>` to minimize the window. Clicking the full-screen button again caused the title bar to fly off screen once more.

As shown in the image below:

![Encountered a situation where window position couldn't be adjusted](https://s2.loli.net/2023/11/13/WUzgqcFfGJmhAsD.png)

This is not a serious issue as I can simply avoid maximizing the window. However, I wanted to provide some feedback in this issue due to its existence. Is this considered a bug?

## Possible Reproduction Steps

- Windows Version: Windows 10 2H22
- Move the taskbar to the top of the desktop

**Comment by CDK6182CHR** [comment]
你好，非常感谢你的反馈。这确实可以算一个Bug。
这个问题应该是由于本项目使用的SARibbon库引起的。我注意到SARibbon库目前已有最新版本，我将尝试换用新版本的SARibbon构建看能否解决问题。

Thank you very much for reminding me this issue. This should be a bug.
This problem is probably caused by the SARibbon library used by this project. I have noticed that SARibbon has published some new versions (than that currently used to build qETRC), and I will try to switch to a new version of SARibbon to see whether this can be sovled.

**Comment by CDK6182CHR** [comment]
在V1.5.3 R46发行版中，已经将SARibbon支持库版本升级到1.0.7，经测试此问题应当已经解决。

The version of the SARibbon library is updated to 1.0.7 in qETRC version 1.5.3 Release 46. As demonstrated by my test, this problem should be solved.
